PLOT_SSR_S_INTEGRITY_G = 1
PLOT_SSR_S_INTEGRITY_E = 2
PLOT_SSR_S_INTEGRITY_C = 4
PLOT_SSR_S_INTEGRITY_R = 8
PLOT_SSR_S_INTEGRITY = PLOT_SSR_S_INTEGRITY_G | PLOT_SSR_S_INTEGRITY_E | PLOT_SSR_S_INTEGRITY_C | PLOT_SSR_S_INTEGRITY_R
PLOT_SSR_C_INTEGRITY_G = 16
PLOT_SSR_C_INTEGRITY_E = 32
PLOT_SSR_C_INTEGRITY_C = 64
PLOT_SSR_C_INTEGRITY_R = 128
PLOT_SSR_C_INTEGRITY = PLOT_SSR_C_INTEGRITY_G | PLOT_SSR_C_INTEGRITY_E | PLOT_SSR_C_INTEGRITY_C | PLOT_SSR_C_INTEGRITY_R

PLOT_SSR_S_R = 1
PLOT_SSR_S_A = 2
PLOT_SSR_S_C = 4
PLOT_SSR_C_0 = 1
PLOT_SSR_IOD = 8
